### ISSUE TITLE
Your desired place for reporting bugs, posting features requests etc.?

### ISSUE THREAD

**Issue by katrinleinweber** [SDM-TIB/TIB_Data_Manager#1]
Hi! Since there is also the [ckan_tib](https://github.com/SDM-TIB/ckan_tib) fork & @yersonrr's original [ckan_tib](https://github.com/yersonrr/ckan_tib), I was wondering where best (in the sense of most useful to the developers) to post issues? Thanks for this info, and kind regards!

**Comment by eiglesias34** [comment]
Hello,

Please but any issues regarding the tib data manager here
https://github.com/SDM-TIB/TIB_Data_Manager
The other repository will be deleted soon.

Sincerely,

Enrique Iglesias

**Comment by katrinleinweber** [comment]
OK, will do. Thanks :-)
